src/Service/OriginKeyService.php
src/Storefront/Page/Checkout/Confirm/AdyenCheckoutConfirmPageLoader.php

Don't break the checkout flow in case the origin key or the payment methods list is missing
Wrong API key therefore origin key cannot be retrieved and paymentMethods cannot be retrieved

General improvements in case of misconfiguration

---

src/Service/PaymentStateDataService.php

This modification updates the state data record related to the context token in order to keep only one record.
Generating a new statedata updates the PaymentStateData table for that token.
Generating a new statedata creates a new record if the token is not present.
**Fixed issue**:  PW-2716

[PW-2716] Update or create statedata for token

---

src/Controller/SalesChannelApiController.php
src/Handlers/PaymentResponseHandler.php
src/Migration/Migration1595336256AdyenPaymentResponse.php
src/Resources/app/storefront/src/checkout/checkout.plugin.js
src/Resources/app/storefront/src/checkout/confirm-order.plugin.js
src/Resources/app/storefront/src/main.js
src/Resources/config/services.xml
src/Resources/views/storefront/page/checkout/confirm/confirm-payment.html.twig
src/Service/PaymentResponseService.php
src/Subscriber/CheckoutSubscriber.php

Payment API endpoint.
Confirm order JS plugin to make Ajax payment call to the backend.
Renamed migration class for consistency.
Renamed event subscriber class to be generic.
NA
**Fixed issue**:  [PW-2741]

[PW-2741] Ajax payments call from checkout

---

src/Resources/config/services.xml

The AdyenAccountOrderController decorator is a public controller and needed the `controller.service_arguments` tag.
Retry of failed payment
**Fixed issue**:  PW-2808

[PW-2808] Tagging AdyenAccountOrderController for public access

---

src/Resources/app/storefront/src/checkout/checkout.plugin.js
src/Resources/app/storefront/src/scss/base.scss
src/Resources/views/storefront/component/payment/payment-fields.html.twig

If an Adyen PM is not selected when opening the methods modal it's contents should be hidden until it is selected.
Open PM modal when an Adyen and non-Adyen PM is selected.
**Fixed issue**:  PW-2810

[PW-2810] Hide PM contents by default

---

src/Handlers/CardsPaymentMethodHandler.php
src/Handlers/PaymentResponseHandler.php
src/Handlers/PaymentResponseHandlerResult.php
src/Handlers/ResultHandler.php

Fix payment status still in progress after refused payment
- Remove unused paymentResponseHandler->finalize()
- Add PaymentResponseHandlerResult->createFromPaymentResponse() to create
result from payment response easier
- Validate 3DS1 MD and PaRes when finalize transaction
3DS1 success/refused
3DS2 success/refused

[PW-2813] Payment status still in progress after wrong 3DS2 payment

---

src/Resources/app/storefront/src/scss/modal.scss
src/Resources/views/storefront/page/checkout/confirm/index.html.twig

After submitting the 3DS2 form, the modal was left there without any content and no status progress. Now it's pretty.
Successful 3DS2 flow

[PW-2811] Add a loader state to the 3DS2 modal

---

src/Handlers/CardsPaymentMethodHandler.php
src/Service/PaymentStateDataService.php

After the payments request is built the plugin will delete the persisted state.data.
Payment call removes the state.data after usage.
**Fixed issue**:  PW-2820

[PW-2820] Remove state.data after it has been used

---

src/Resources/app/storefront/src/checkout/checkout.plugin.js
src/Resources/app/storefront/src/scss/base.scss
src/Resources/snippet/en_GB/messages.en-GB.json
src/Resources/views/storefront/component/payment/payment-fields.html.twig
src/Resources/views/storefront/page/checkout/confirm/confirm-payment.html.twig
src/Service/PaymentStateDataService.php
src/Subscriber/PaymentSubscriber.php

The payment methods modal can be opened after the state.data has been saved for a PM. If that PM is selected we want to provide feedback that the information can be updated instead of showing the form.
Selecting Cards PM after a state.date has been saved
**Fixed issue**:  PW-2812

[PW-2812] Hide PM contents when there's state.data already stored for it

---

src/Resources/app/storefront/src/checkout/checkout.plugin.js
src/Resources/views/storefront/component/payment/payment-fields.html.twig

The plugin uses a generic data attribute to store essential information to work, like the payment method id. This can potentially conflict with other payment method providers, including native ones if they start looking for this attribute. This change includes a prefix for this with the name `adyen` so that conflicts are harder to happen.
Successful 3DS2 payment
**Fixed issue**: PW-2826

Improve front-end reliability

---

src/Resources/views/storefront/component/payment/payment-action-modal.html.twig
src/Resources/views/storefront/page/account/order/index.html.twig
src/Resources/views/storefront/page/checkout/confirm/index.html.twig

The 3DS2 modal is not appearing in the change order page because the HTML for the modal is missing. This Pull Request fixes that and also extracts the modal markup to a separate template file.
- 3DS2 payments in both checkout and change order pages
**Fixed issue**: PW-2809

Fix 3DS2 modal in change order page

---

src/Controller/ApiTestController.php
src/Resources/app/administration/src/component/adyen-config-check-button/index.js
src/Resources/app/storefront/src/checkout/confirm-order.plugin.js

Improves the messages from checking the configuration values.
Clicking the button in the plugin config screen

Improve error messages in the plugin config test

---

src/AdyenPaymentShopware6.php
src/Controller/SalesChannelApiController.php
src/Handlers/AbstractPaymentMethodHandler.php
src/Handlers/CardsPaymentMethodHandler.php
src/Handlers/IdealPaymentMethodHandler.php
src/Handlers/KlarnaPaymentMethodHandler.php
src/Handlers/SepaPaymentMethodHandler.php
src/Handlers/SofortPaymentMethodHandler.php
src/PaymentMethods/IdealPaymentMethod.php
src/PaymentMethods/KlarnaPaymentMethod.php
src/PaymentMethods/PaymentMethods.php
src/PaymentMethods/SepaPaymentMethod.php
src/PaymentMethods/SofortPaymentMethod.php
src/Resources/app/storefront/src/checkout/checkout.plugin.js
src/Resources/config/services.xml
src/Resources/views/storefront/component/payment/payment-fields.html.twig
src/Subscriber/PaymentSubscriber.php

New payment methods have been added to be installed and picked up by the generic component in the checkout page. In order to outsource the payment handler logic an abstract class was created along with a static function to fetch the PM code in the Payment Subscriber using the handler.
All the payment methods have been added to services.xml with all the classes' dependencies, maybe there's a way to simplify those declarations.
New frontend validation must be implemented to accommodate all the payment methods.
Some API endpoints were moved from v2 to v3 since that version was removed from S6.3.
New payment methods are installed and rendered in the frontend.
**Fixed issue**:  PW-2788

[PW-2788] Add payment methods to the plugin and adjust card payment handler

---

src/Handlers/AbstractPaymentMethodHandler.php
src/Handlers/ResultHandler.php
src/Storefront/Controller/RedirectResultController.php

This new redirect data adds `redirectFromIssuerMethod`, `redirectToIssuerMethod` and `returnUrl` to the /payments request. The sales channel API context token is the same after the payment and the order can be finished.
The redirect response from issuers page is now GET and not POST. The session is maintained without ignoring the SameSite cookie security.
/payments request contains new redirect data
Redirect payments are handled via GET
**Fixed issue**:  PW-2822

Adding redirect data to /payments call

---

src/Handlers/AbstractPaymentMethodHandler.php
src/Handlers/CardsPaymentMethodHandler.php
src/Handlers/IdealPaymentMethodHandler.php
src/Handlers/KlarnaPayLaterPaymentMethodHandler.php
src/Handlers/KlarnaPayNowPaymentMethodHandler.php
src/Handlers/ResultHandler.php
src/Handlers/SepaPaymentMethodHandler.php
src/Handlers/SofortPaymentMethodHandler.php
src/PaymentMethods/KlarnaPayLaterPaymentMethod.php
src/PaymentMethods/KlarnaPayNowPaymentMethod.php
src/Resources/app/storefront/src/checkout/checkout.plugin.js
src/Resources/config/services.xml

This PR adds order item lines to the payments request in order to support open invoice PMs. It also includes Klarna Pay Later and Pay Now.
The services.xml abstract payment method handler declaration now is parent to the concrete handlers and some old use statements were removed.
Payments with Klarna Pay Later and Pay Now.
Payments with 3DS and non 3DS cards.
**Fixed issue**:  PW-2786

[PW-2786] OpenInvoice lines support and Klarna PMs

---

src/Handlers/PaymentResponseHandler.php
src/Resources/app/storefront/src/checkout/checkout.plugin.js

The /payments response needs to be stored even for ERROR results otherwise the payment status will fail 
Authorised payment
Refused payment
Error payment

[PW-2838] Investigate if payment response needs to be stored for ERROR payment result code

---

src/Entity/Notification/NotificationEntity.php
src/Entity/PaymentResponse/PaymentResponseEntity.php

The Notifications and Payment Response entities had invalid definitions.
**Fixed issue**:  Fixes #50

Fixing invalid entity definitions

---

src/Resources/app/storefront/src/checkout/confirm-order.plugin.js
src/Resources/config/services.xml
src/Resources/views/storefront/component/payment/adyencheckout.html.twig
src/Resources/views/storefront/component/payment/payment-fields.html.twig
src/Subscriber/PaymentSubscriber.php

Don't change the behaviour of non adyen payment methods.
Check the pluginId of the payment method and if it's not from adyen do not interfere with the default process.

[PW-2937] Make plugin compatible with different payment methods

---

src/Handlers/AbstractPaymentMethodHandler.php
src/Handlers/ResultHandler.php
src/Resources/config/services.xml
src/Service/CheckoutService.php
src/Service/CheckoutUtilityService.php
src/Service/ClientService.php
src/Service/ConfigurationService.php
src/Service/NotificationReceiverService.php
src/Service/OriginKeyService.php
src/Service/PaymentDetailsService.php
src/Service/PaymentMethodsService.php
src/Subscriber/PaymentSubscriber.php

The plugin used to fetch the default configuration for all sales channels for all operations. With this PR the API calls make use of the current sales channel configuration values.
The redirect of 3DS1 payments on non-default sales channels fails because Shopware generates a finishUrl for the default sales channel and not for the current one.
3DS and non-3DS payments in default and non default sales channels (3DS1 fails when using a non-default sales channel with no default configuration).
Klarna Pay Now and Klarna Pay Later in default and non default sales channels.
**Fixed issue**:  PW-2975 fixes #46

[PW-2975] Adding support for multiple sales channels configurations

---

src/Controller/SalesChannelApiController.php
src/Resources/app/storefront/src/checkout/checkout.plugin.js
src/Resources/app/storefront/src/validator/FormValidatorWithComponent.js
src/Resources/config/services.xml
src/Service/PaymentResponseService.php
src/Service/PaymentStatusService.php

A 500 error can occur 
- when the customer doesn't complete the component before saving the payment method configuration therefore the state.data is missing from the /payments request because of the missing frontend validation
- when the customer arrives to the payment methods list page while their preferred payment method is already selected therefore they don't change and store it but places the order right away
Wrong details filled in the checkout component - validation won't let the customer to save the changes anymore
Payment method change is not saved but order is placed - redirects the user to the finalize page and shows an error message while the payment is failed in the admin page

[PW-3004] Fix payment when attempt without state.data stored but requested from db

---

src/Handlers/AbstractPaymentMethodHandler.php
src/Handlers/PaymentResponseHandler.php
src/Handlers/ResultHandler.php

This commit refactors how exceptions are handled in the `pay` and `finalize` methods. It refactors some other parts of the class to make the approach as elegant as before, while maintaining enough room for handling different exceptions or changing how the exceptions are handled later. The downside is having to manage two pieces of code, but it would still fall into the [rule of three](https://en.wikipedia.org/wiki/Rule_of_three_(computer_programming))
None

Refactor exception handling

---

src/Exception/PaymentCancelledException.php
src/Exception/PaymentFailedException.php
src/Handlers/AbstractPaymentMethodHandler.php
src/Handlers/PaymentResponseHandler.php
src/Handlers/PaypalPaymentMethodHandler.php
src/Handlers/ResultHandler.php
src/PaymentMethods/PaypalPaymentMethod.php
src/Resources/app/storefront/src/checkout/checkout.plugin.js
src/Resources/config/services.xml

Add paypal support in checkout without using the adyen checkout components
Known issue, will be fixed by shopware in the core: https://issues.shopware.com/issues/NEXT-8636
When the customer cancels the payment the payment status will be failed in the admin and the customer will see a message related to failed payment and not cancelled payment.
paypal successful payment
paypal cancelled payment

[PW-2787] New paypal integration

---

src/Controller/SalesChannelApiController.php

Shopware deprecates API versions constantly, these can be made dynamic and should be tested in 6.3 versions of the platform.
Payment with cards

Make API version in routes dynamic

---

src/Resources/config/services.xml
src/Storefront/Controller/AdyenAccountOrderController.php

Adjust constructor to shopware 6.3 in AdyenAccountOrderController
Drop support for shopware 6.2.*
After failed payment a new payment can be initiated in the account orders page

[PW-3042] Fix account order construct incompatibility with 6.3.*

---

src/Resources/config/services.xml
src/Storefront/Controller/AdyenAccountOrderController.php

`AdyenAccountOrderController` was a service decorating and extending `AccountOrderController`, this broke implementations on Shopware versions that changed the constructor’s signature.
We're moving that logic into a storefront controller accessible through an overridden route. The controller then adds the extra parameters to the RequestBag.
Shopware 6.3.2.0
Editing the order's payment methods.
**Fixed issue**:  PW-3190 Fixes #71

[PW-3190] Moving AdyenAccountOrderController from a decorated service to a controller

---

src/AdyenPaymentShopware6.php
src/Resources/config/services.xml
src/Service/ClientService.php

The plugin used to get the module version from the composer file and this caused problems with the directory structure. We're switching to the plugin entity to fetch this value now, leveraging the cache system.
Shopware 6.3.2.0
`getModuleVersion()` queries the plugin entity to get the installed version. In production mode this value is then saved in cache for future use.
**Fixed issue**:  PW-2842 Fixes #49

[PW-2842] Getting module version from plugin entity

---

src/AdyenPaymentShopware6.php

If during uninstallation the user selects "Remove all plugin data permanently" the configuration keys used by the bundle are deleted and the plugin's tables are dropped.
Payment methods are not removed as the IDs could still be referenced from order_transaction.
Shopware 6.3.2.0
Uninstall with "Remove all plugin data permanently" checked: Deactivates all payment methods, deletes configuration keys and drops adyen tables.
Uninstall with "Remove all plugin data permanently" unchecked: Deactivates all payment methods.
**Fixed issue**:  PW-2839

[PW-2839] Removing plugin data on uninstall

---

src/Resources/views/storefront/component/payment/payment-fields.html.twig

In Shopware 6.3.2.1 the `payment` entity in `payment-fields.html.twig` doesn't include `pluginId`. We're checking for the formatted payment method handler identifier to apply the Adyen class instead.
Shopware 6.3.2.1
Adyen payment methods include the Adyen class in the frontend used for order form interception.

Changing twig if statement to check if payment method handler contains 'handler_adyen_'

---

src/Handlers/PaymentResponseHandler.php

The plugin attempted to move the order with do_pay more than once for some payments.
e.g. SEPA might return 'Received', then both the `pay()` and `finalize()` functions tried to process it. `finalize()` doesn't need to move the order because the response was sync.
Shopware 6.3.2.1
'Received' payments move the oder to in_progress on `pay()` sync response only.

Checking if order is 'in_progress' before doing do_pay transition

---

src/Handlers/AbstractPaymentMethodHandler.php
src/Resources/app/storefront/src/checkout/checkout.plugin.js

This adds support for saving card details. A future pull request will enable paying with stored credit cards.
The data is stored in Adyen servers securely, and only a token is shared between the plugin and Adyen.
Payment with credit cards, asking to save the card details or not.

[PW-2789 ] Enable save card details

---

src/Resources/config/services.xml
src/Service/PaymentMethodsService.php
src/Service/Repository/OrderRepository.php
src/Subscriber/PaymentSubscriber.php

Use the order currency and order total amount for the paymentMethods request in case the order is already created (edit order)
Use the cart currency and cart total amount when the payment happens in the checkout
paymentMethods request in order edit
paymentMethods request in checkout

[PW-3301] /paymentMethods call in order edit is not using the order data

---

.github/CODEOWNERS
src/Resources/config/services.xml
src/ScheduledTask/ProcessNotifications.php
src/ScheduledTask/ProcessNotificationsHandler.php
src/ScheduledTask/ScheduleNotifications.php
src/ScheduledTask/ScheduleNotificationsHandler.php

As part of the effort to add support for payment notifications,
We introduce 2 scheduled tasks for `ProcessNotifications` and `ScheduleNotifications` which run every minute
Logged messages appear every minute in `var/log/adyen/notification.log`
**Fixed issue**:  PW-3587

Add minutely scheduled tasks for notifications

---

src/Handlers/GiroPayPaymentMethodHandler.php
src/PaymentMethods/GiroPayPaymentMethod.php
src/Resources/app/storefront/src/configuration/adyen.js
src/Resources/config/services.xml

Add GiroPay support
Depends on: #95
Giropay payment method

Add GiroPay payment method

---

src/Entity/Notification/NotificationEntity.php
src/Entity/Notification/NotificationEntityDefinition.php
src/Migration/Migration1607529255AdyenNotification.php

Add new filed scheduled_processing_time via migration to the adyen_notification table.
Check new table column exists after reinstalling or updating the plugin
**Fixed issue**:  PW-3588

[PW-3588] migration to add scheduled_processing_time to notification

---

src/Entity/Notification/NotificationEntity.php
src/Entity/Notification/NotificationEntityDefinition.php
src/Service/ConfigurationService.php
src/Service/NotificationReceiverService.php
src/Service/NotificationService.php

Add method in `NotificationService` to set the scheduled processing time on a notification, which will be triggered via the scheduled task (shopware cron job) for every notification that needs to be scheduled.
`scheduled_processing_time` field is updated in database.
the whole flow can be tested when the scheduled task is implemented in a subsequent PR
**Fixed issue**:  PW-3591

[PW-3591] add method in NotificationService to set scheduled_processing_time on Notification

---

.github/workflows/main.yml

For our test workflows, the virtual environment `ubuntu-latest` [now includes PHP 8.0.0](https://github.com/actions/virtual-environments/pull/2162) and this is installed by default. Because of this our new tests are [failing due to many packages depending on PHP ^7.*](https://github.com/Adyen/adyen-shopware6/runs/1570111729?check_suite_focus=true) 
This PR applies a fix to pin the version of PHP to 7.4
Main workflow runs successfully

Set PHP version to 7.4 in main workflow

---

.github/workflows/main.yml
src/Service/ConfigurationService.php
src/Service/NotificationReceiverService.php
src/Service/NotificationService.php

Retrieve a collection of notifications:
* between T-1 day and T-1 minute, 
* that are not done and 
* not being processed and 
* `scheduled_processing_time` is not null, 
* limited to 100 rows at a time, 
* sorted by `scheduled_processing_time`
Returns collection that fits above criteria
**Fixed issue**:  PW-3589

[PW-3589] Add getScheduledUnprocessedNotifications() to NotificationService

---

src/Service/NotificationService.php

Add new method to `NotificationService` for retrieving unprocessed notifications.
Returns a `NotificationEntityCollection` of max 100 records at a time
Ordered by creation timestamp
Returns `NotificationEntityCollection` with max 100 notifications ordered by `created_at` datetime
**Fixed issue**:  PW-3590

PW-3590 get unscheduled notifications in NotificationService

---

src/Command/FetchPaymentMethodLogosCommand.php
src/Migration/Migration1609373668AdyenMediaFolder.php
src/PaymentMethods/CardsPaymentMethod.php
src/PaymentMethods/GiroPayPaymentMethod.php
src/PaymentMethods/IdealPaymentMethod.php
src/PaymentMethods/KlarnaAccountPaymentMethod.php
src/PaymentMethods/KlarnaPayLaterPaymentMethod.php
src/PaymentMethods/KlarnaPayNowPaymentMethod.php
src/PaymentMethods/OneClickPaymentMethod.php
src/PaymentMethods/PaypalPaymentMethod.php
src/PaymentMethods/SepaPaymentMethod.php
src/PaymentMethods/SofortPaymentMethod.php
src/Resources/config/services.xml
src/ScheduledTask/FetchPaymentMethodLogos.php
src/ScheduledTask/FetchPaymentMethodLogosHandler.php
src/Subscriber/PaymentSubscriber.php

Each payment method has a function: public function getLogo(): string to retrieve the logo but we return the https://checkoutshopper-live.adyen.com/checkoutshopper/images/logos/medium/sofort.png' url instead of downloading it and providing it from the server of the merchant.
Show the logos using the resources from the server.
Fix involves creation of scheduled task  to fetch logos weekly and upload them to create Shopware media entities and then attaching them to the payment_method entities.
Weekly cron will first delete the old media and then recreate new ones from the downloaded file
Fallback is that in the case where a remote URL is temporarily unreachable, the payment method will be skipped, thereby preserving its media from the previous run.
New Command `adyen:fetch-logos` is also …

PW-3120 add weekly cron to fetch PM logos

---

src/Resources/config/services.xml
src/Service/NotificationReceiverService.php
src/Storefront/Controller/NotificationReceiverController.php

Use: https://github.com/Adyen/adyen-php-api-library/blob/develop/src/Adyen/Service/NotificationReceiver.php services instead of maintaining the same code in shopware6 here: https://github.com/Adyen/adyen-shopware6/blob/develop/src/Service/NotificationReceiverService.php
Receiving of notifications still works the same:
- Authentication checks, Hmac checks still work as expected
- Test notifications still return expected results

[PW-2843] implement notification auth from the library

---

src/Entity/Notification/NotificationEntityDefinition.php

additional_data field was unable to receive very long data in notifications because it was set to string in entity definition
Send notification with very long (longer than 255 chars) additional data

PW-3049 bugfix fix additional_data definition in adyen notifications

---

src/Controller/ApiTestController.php

Only keep merchant account and remove the rest of config fields for the test.

[PW-3117] remove extra fields in api test

---

src/Controller/StoreApiController.php
src/Resources/app/storefront/src/checkout/confirm-order.plugin.js
src/Resources/config/services.xml
src/Resources/views/storefront/page/checkout/confirm/confirm-payment.html.twig
src/Subscriber/PaymentSubscriber.php

Sales Channel API is being deprecated in S6.4 https://docs.shopware.com/en/shopware-platform-dev-en/sales-channel-api/sales-channel-context-api
Reimplement all the methods in SalesChannelApiController in a new custom StoreApiController and under the store-api scope.
Update route references in PaymentSubscriber and generate checkoutOrderUrl using store-api
Checkout flow

[PW-3768] replace usage of sales-channel-api with store-api

---

src/Resources/app/administration/src/component/adyen-config-check-button/index.js

When testing API details the All Sales Channels form data and config was always used.
If a user enters different API details in a separate sales channel form it should be possible to test those as well.
This PR fixes it.
Test API config with selected sales channel

[PW-3114] use config from selected sales channel when testing api config

---

src/Resources/app/storefront/src/checkout/confirm-order.plugin.js
src/Subscriber/PaymentSubscriber.php

The check to remove OneClick from the PM list was wrong.
In this new check we're only removing the Shopware PM from the list if:
- It isn't in the `/paymentMethods` response.
- It is OneClick but OneClick isn't in the `/paymentMethods` response.
The orderId was not being fetched successfully from the place order response.
Loading the PM list with no OneClick method removes the OneClick option.
Loading the PM list with OneClick methods doesn't remove the OneClick option.
**Fixed issue**:  PW-3624

[PW-3624] Fixing check to remove OneClick from PM list

---

src/Controller/StoreApiController.php
src/Handlers/PaymentResponseHandler.php
src/Resources/app/storefront/src/checkout/confirm-order.plugin.js
src/Resources/config/services.xml
src/Service/PaymentResponseService.php

From the issue created in GitHub (https://github.com/Adyen/adyen-shopware6/issues/127)
Pay with failing card details, then pay with one of redirect payment methods.
Pay with failing  redirect payment method, then pay with another redirect PM
Pay with failing card, the pay with valid card details
**Fixed issue**: #127 #92

[PW-3922] Fix problem with completing a failed payment

---

src/Handlers/PaymentResponseHandler.php
src/Handlers/ResultHandler.php

[PW-3983] is solved by setting the `checkoutThreeDS1AuthorisationBehavior` ADP to `Auto` in the Customer Area.
This PR only introduces a minor change to check that the payment details exist before attempting to send the request to the [/payment/details API](https://docs.adyen.com/api-explorer/#/CheckoutService/v66/post/payments/details)
3DS1 payment on Chrome v80+

[PW-3983] small fix, validate details in resultHandler

---

src/Subscriber/PaymentSubscriber.php

Fixed bug in payment methods filter for checkout page, that allowed PMs not returned by the `/paymentMethods` call to still be displayed in checkout
iDeal does not show up for Belgium address
OneClick PMs do show up if they exist

[PW-3652] bug fix in payment methods filter

---

src/Handlers/AbstractPaymentMethodHandler.php
src/Resources/config/services.xml

If the customer belongs to a "Tax display = Net" group the order line's price is already tax exclusive. In this PR a check with TaxDetector is used to include or exclude the tax from the lines in the payments request.
"Tax display = Net" group, the tax is not subtracted from the order lines.
"Tax display = Gross" group, the tax is subtracted from the order lines.
**Fixed issue**: PW-3938

[PW-3938] Using TaxDetector to subtract tax from order lines

---

src/Handlers/AbstractPaymentMethodHandler.php
src/Resources/config/services.xml

Removing the dependency on TaxDetector and using taxStatus to determine if the order is type Net or Gross.
"Tax display = Net" group, the tax is not subtracted from the order lines.
"Tax display = Gross" group, the tax is subtracted from the order lines.
**Fixed issue**:  PW-3938

[PW-3938] Switching to taxStatus to determine if the order tax type is Net or Gross

---

src/Subscriber/PaymentSubscriber.php

I introduced a bug in the previous PR ([[PW-4180]](https://github.com/Adyen/adyen-shopware6/pull/141)) by switching to the event context [here](https://github.com/Adyen/adyen-shopware6/pull/141/files#diff-94c3ec56b7a92d80e1953086cde504fc4919edaefee871ac714fdf3fd3e57562R403)
This causes the following error:
```
Argument 2 passed to Shopware\Core\Checkout\Payment\DataAbstractionLayer\PaymentMethodRepositoryDecorator::search() must be an instance of Shopware\Core\Framework\Context, instance of Shopware\Core\System\SalesChannel\SalesChannelContext given, called in /home/vagrant/shopware-dev/vendor/adyen/adyen-shopware6/src/Subscriber/PaymentSubscriber.php on line 403
```

PW-4180 bugfix revert to default context

---

src/Core/Checkout/Order/Aggregate/OrderTransaction/OrderTransactionExtension.php
src/Resources/config/services.xml

Github issue https://github.com/Adyen/adyen-shopware6/issues/133
bin/console dal:validate returns the following error in v6.3.5.1
* Missing reverse one to many association for Adyen\Shopware\Entity\PaymentResponse\PaymentResponseEntityDefinition <-> Shopware\Core\Checkout\Order\Aggregate\OrderTransaction\OrderTransactionDefinition (orderTransaction)
This PR adds the missing extension
**Fixed issue**: Closes #133

[PW-4158] add missing reverse relationship

---

src/Entity/Notification/NotificationEntity.php
src/NotificationProcessor/NotificationEventCodes.php
src/NotificationProcessor/NotificationProcessor.php
src/NotificationProcessor/NotificationProcessorFactory.php
src/NotificationProcessor/RefundNotificationProcessor.php
src/ScheduledTask/ProcessNotificationsHandler.php
src/Service/Repository/OrderRepository.php

Create REFUND notification processor.
Transition order transactions to refunded/refunded_partially when notification is received and handle illegal state transitions
open -> refunded (illegal: moves to paid and then to refunded) ✅
refunded -> refunded (illegal: skips) ❌
refunded -> [other] (illegal: skips) ❌
paid -> refunded ✅
cancelled -> refunded ✅
refunded_partially -> refunded ✅
**Fixed issue**:  Resolves #157

[PW-4474] add refund notification processor

---

src/Struct/AdyenPaymentMethodDataStruct.php
src/Subscriber/Response/PaymentMethodRouteResponseSubscriber.php

Changing payment-method extension to return only payment method config like below:
```json
...
"extensions": {
"adyenData": {
"type": "paypal",
"paymentMethodConfig":  {
"configuration": {
"merchantId": "MERCHANT_ACCOUNT",
"intent": "capture"
},
"name": "PayPal",
"type": "paypal"
},
"apiAlias": "adyen_shopware_struct_adyen_payment_method_data_struct"
}
},
```
instead of previous structure:
```json
...
"extensions": {
"adyenData": {
"type": "paypal",
"paymentMethodsResponse": {
"paymentMethods": {
"1": {
"configuration": {
"merchantId": "MERCHANT_ACCOUNT",
"intent": "capture"
},
"name": "PayPal",
"type": "paypal"
}
}
},
"apiAlias": "adyen_shopware_struct_adyen_payment_method_data_struct"
}
},
```
See [this discussion](https://github.com/Adyen/adyen-shopware6/pull/162#discussion_r638758389) …

Return only payment method config for each PM extension

---

src/Handlers/AbstractPaymentMethodHandler.php

When product variants inherit the parent's name the variant itself doesn't have a name property, it has a translation instead. This means that in those cases the openinvoice lineItems were not filling the description value. Here a translation on the field `name` is being fetched instead, which works for both parent and variants.
Openinvoice payments with:
- Products with no variants.
- Products with variants.
- Variants.
**Fixed issue**:  PW-4704 #167

[PW-4704] Using product's name translation for openinvoice lineitem description

---

src/Resources/app/storefront/src/scss/base.scss

Paypal is rendering an iframe instead of opening a new window for the login in case the customer is using firefox on ios. The PR can be found [here](https://github.com/paypal/paypal-checkout-components/pull/269/files#diff-69d37eb033f3d7b6d25e51188e38b2709976a4a72894c20d3fc4805b2a781699R346 ). 
Whenever a payment is started Shopware adds a `has-element-loader` class to the html body which applies `pointer-events: none;` on the child elements, therefore the paypal iframe as well. Since it's applied there the customer cannot click on the form elements or close the popup.
This PR makes sure the pointer-events is set to auto for the paypal iframe.
IOS firefox paypal
Chrome web paypal

[PW-5011] Paypal button is not working in Firefox on IOS mobile

---

src/Framework/Cookie/AdyenCookieProvider.php

Missing `snippet_name` in cookies breaks in SW v6.4.
Add default name for all hidden snippets
Update cookies list to the new checkout component version's cookies
**Fixed issue**: Resolves #196

[PW-5253] add snippet_name for all cookies.

---

src/Handlers/AbstractPaymentMethodHandler.php

We were using the wrong format (d-m-Y) while sending the request to Checkout API, however Checkout API only accepts the format Y-m-d and if you were to pass the wrong format, it would throw 702 validation error. 
Card payment with shopper birthday enabled
**Fixed issue**: PW-5658

[PW-5658] Fixed the wrong DoB format to fit Checkout API

---

src/Handlers/AbstractPaymentMethodHandler.php
src/Resources/app/storefront/src/checkout/confirm-order.plugin.js

We want to only have giftcards work via HPP. Hence it doesn't make sense for the customer to input the fields in the component and then again in the HPP.
- Removed logic for mounting giftcard components in checkout
- Added `brand` to  giftcard payment request in handler
Giftcard payments don't render component and redirect to HPP fallback

[PW-5892] dont render giftcard component in checkout and use HPP fallback

---

README.md

The `master` branch in this repo has been renamed to `main`.

Renaming master to main in README.md

---

src/Handlers/AbstractPaymentMethodHandler.php

The idea behind using the protected function instead of private is to be able to extend the AbstractPaymentMethodHandler so that the recurringProcessingModel can be passed as a parameter. Extending the AbstractPaymentMethodHandler would enable controlling the request parameters.
Tested with credit card payment and refund.

[PW-5944] Change the private function preparePaymentsRequest to protected

---

src/Controller/AdminController.php
src/Service/RefundService.php

Send the amount in cents correctly when processing a refund.
* Float refund amount
* Integer refund amount

[PW-6169] - Send amount in cents correctly

---

src/ScheduledTask/ProcessNotificationsHandler.php

Remove dependency on REFUND_FAILED constant from the `\Adyen\Webhook\PaymentStates`

[PW-6142] remove REFUND_FAILED as a webhook payment state

---

src/Controller/AdminController.php
src/Service/RefundService.php
src/Service/Repository/AdyenRefundRepository.php

Use order transaction ID as idempotency key to avoid sending duplicate requests.
Update idempotency key to last saved refund if refund total amount is not exceeded.
Avoid saving refund with duplicate pspReference
Multiple refund requests made at the same time
Subsequent refund requests with partial amounts

[PW-6546] set idempotency key to avoid duplicated refund requests

---

src/Service/Repository/SalesChannelRepository.php

If a sales channel has more than one domain name assigned to it, 3DS flow breaks due to incorrect origin value in the request although returnUrl is correct. Domain name for the origin is being fetched according to creation order from DB. If the shopper is not on this domain, error occurs.
Default sales channel url is now being defined from the default domain of hreflang integration if it is set.

[PW-6477] - Get sales channel url from the hreflang integration if it is set

---

src/Controller/StoreApiController.php
src/Resources/app/storefront/src/checkout/confirm-order.plugin.js
src/Resources/views/storefront/page/checkout/confirm/confirm-payment.html.twig
src/Service/PaymentResponseService.php
src/Service/Repository/OrderTransactionRepository.php
src/Subscriber/PaymentSubscriber.php

PayPal pop-up cancellation was blocking the change of payment method on the checkout page.
- PayPal (cancel) -> PayPal (auth)
- PayPal (cancel) -> CC 3ds2 (cancel on authentication) -> Klarna (auth)
- PayPal (cancel) -> PayPal (cancel) -> iDeal (auth)

[PW-6820] - Prevent PayPal cancellation block the payment method change on checkout

---

src/Subscriber/PaymentSubscriber.php

This fixes an issue where the checkbox for saving card details was never displayed.
This was caused because we filtered out the oneclick payment method from the list of available payment methods based on `/paymentMethods` response before then checking for oneclick to determine if merchant has enabled it in the store. (🤯 I know)
Fix: check if oneclick is enabled before filtering based on paymentMethods response
Save for next payment checkbox is displayed when oneclick is enabled

Fix save payment details config

---

src/Handlers/AbstractPaymentMethodHandler.php

Allows to use custom line items in cart and order.  In the current case only products and promotions can use in a cart and order. If a custom entity will used, the payment process interrupt with an error.
* create a custom line item with processor like a bonus coupon or voucher
* add a line item to the cart
* run checkout

allows to use custom line item types in cart & order

---

src/Handlers/AbstractPaymentMethodHandler.php
src/Service/Repository/SalesChannelRepository.php

When more than one domain is set on the same sales channel, 3DS2 payments coming from the second..last domains always get stuck. This is happening because we set the origin value in the payment request by either using the hreflang default domain (if set) or else we simply get the first domain registered to the sales channel. This becomes an issue for merchants with multiple (sub-)domains e.g based on language es.example.com, de.example.com
To fix this, when making the payment request instead of getting the origin value by picking the first domain on the sales channel, use the origin from the base URL of the transaction request.
- 3DS2 payments in multiple domains in the same sales channel
Fixes #267

[PW-6992] Fix origin issue with multiple domain in one storefront

---

src/Resources/config/services.xml

When a new payment method is created in the Shopware 6 admin section (Settings -> Payment Methods -> Add Payment Method) it is assigned the handler `Shopware\Core\Checkout\Payment\Cart\PaymentHandler\DefaultPayment` which is originally registered by Shopware in [payment.xml](https://github.com/shopware/platform/blob/trunk/src/Core/Checkout/DependencyInjection/payment.xml#L115).
By overriding this definition in our [services.xml](https://github.com/Adyen/adyen-shopware6/blob/02384c8f95456defc4b871b80750858b2481b692/src/Resources/config/services.xml) file and not including the `shopware.payment.method.sync` tag, we prevent Shopware from registering it as a payment handler in [PaymentHandlerRegistry](https://github.com/shopware/platform/blob/trunk/src/Core/Checkout/Payment/Cart/PaymentHandler …

[PW-7212] Fix issue with custom payment methods

---

src/Service/Repository/SalesChannelRepository.php

As a fallback for headless sales channel in which the context object has neither a `domainId` nor a `salesChannel.hreflangDefaultDomainId`, revert to fetching the first available domain assigned to the sales channel
Payment request via postman with headless sales channel token
Resolves #302

[PW-7299] select first domain as fallback where domain ID is not set

---

src/Handlers/GooglePayPaymentMethodHandler.php
src/PaymentMethods/GooglePayPaymentMethod.php
src/Resources/app/storefront/src/checkout/confirm-order.plugin.js
src/Resources/app/storefront/src/configuration/adyen.js
src/Service/PaymentMethodsFilterService.php

`googlepay` tx_variant is supported without a configuration change on the Shopware 6 side.
This tx_variant could be enabled from the Adyen Customer Area after disabling the old one `paywithgoogle`.
- GooglePay with both tx_variants

[PW-7429] - Support new GooglePay tx_variant

---

src/ScheduledTask/Webhook/AuthorisationWebhookHandler.php

Failed authorisation notification is overriding if there is any successful authorisation notification. 
State change check added to see before any transitional change.
- 3DS failed + iDeal successful
- 3DS failed
- iDeal successfuk
Fixes #311

[PW-7512] - Fix first failed payment overwrites second successful payment

---

src/Handlers/AbstractPaymentMethodHandler.php
src/Service/PaymentMethodsService.php
src/Service/PaymentRequestService.php

Solves issue https://github.com/Adyen/adyen-shopware6/issues/308
When housenumber includes '-' it wasn't splitted from street by the old RegEx. This was used by customers to give a suite number. The new RegEx allows this.
Using "106-19 Dallas Road" in street field
**Fixed issue**:  308

allow '-' in housenumber when splitting

---

src/Resources/views/storefront/component/payment/payment-method.html.twig

Shopware does not load the `component_payment_method_description_text` block if payment method description is missing, see [here](https://github.com/shopware/platform/blob/trunk/src/Storefront/Resources/views/storefront/component/payment/payment-method.html.twig#L40), and this results in our component not being loaded and therefor payments fail with the error `Payment details are missing.`
Extend the parent block `component_payment_method_description` instead to load our plugin component.
Pay with component when the payment method has no description
Test for Wallet payment method, Paypal

[PW-7528] change block in which payment component is rendered

---

src/Resources/app/storefront/src/checkout/confirm-order.plugin.js
src/Resources/app/storefront/src/scss/base.scss
src/Resources/views/storefront/component/payment/payment-action-modal.html.twig

3DS2 modal size fixed in order to fit the modal wrapper.

[PW-7690] - Fix 3DS2 modal size

---

src/Service/CaptureService.php
src/Service/RefundService.php

- Ignoring saleschannel was preventing to create refund and capture request for different merchant account
Capturing and refund requests are ignoring the order saleschannel, which prevents loading the configuration specific to the saleschannel and only loads the merchant account from the "All sales channel" configuration.
If a saleschannel has a different merchant account then the default configuration, capture and refund request fail.
Premises:
- Two sales channel
- UK
- Merchant Account value: UK
- Germany
- Merchant Account value: DE
Scenario one:
- Leave "All sales channel" Merchant Account blank
- Request a refund for an order in saleschannel Germany
- Request fails: Merchant Account is blank
- Request a refund for an order in saleschannel UK
- Request fails: Merchant Account is …

[SHW-450] Fix saleschannel ignored for capture and refund request

---

src/Handlers/AbstractPaymentMethodHandler.php
src/Resources/config/services/payment-handlers.xml

Fixes the referenced issue.
**Fixed issue**: https://github.com/Adyen/adyen-shopware6/issues/338
I tested it for my scenario and it works correctly. It should also work correctly for all the other scenarios but please test those as well.

Avoid potential duplicate base url for redirect result route. (Fixes: #338)

---

src/Resources/config/services/repositories.xml
src/Service/Repository/SalesChannelRepository.php
src/Subscriber/PaymentSubscriber.php

Obtaining locale from the sales channel repository was being resulted in getting the default locale value even if the selected language was different. That behaviour caused wrong locale was being sent to the Adyen Web components configuration.
Instead of fetching the locale from DB according to the sales channel default values, now it is being fetched from sales channel context. 
- Different language setups on the store with correct component language setup

[PW-8180] Fix wrong language on checkout component

---

src/Handlers/AbstractPaymentMethodHandler.php
src/Service/PaymentRequestService.php

`productUrl` parameter builder updated in the line item builders since the `getSeoUrls()` can be null and not reliable for product URL generation.
- Klarna payment
- Manual capture
Fixes #344

[PW-7981] Change productUrl builder for line items

---

src/Handlers/AbstractPaymentMethodHandler.php

When the storefront domain URL has a trailing slash, the return URL generated contains 2 consecutive slashes. e.g. `https://example.com//adyen/redirect-result`
This fix trims the trailing slash from the domain if it exists

fix extra leading slash in return URL

---

src/Controller/AdminController.php
src/Handlers/PaymentResponseHandler.php
src/Handlers/PaymentResponseHandlerResult.php
src/Resources/app/administration/src/component/adyen-partial-payments/adyen-partial-payments.html.twig
src/Resources/app/administration/src/component/adyen-partial-payments/index.js
src/Resources/app/administration/src/component/adyen-refund/index.js
src/Resources/app/administration/src/service/adyenService.js
src/Resources/app/administration/src/snippet/en_GB.json
src/Resources/app/administration/src/sw-order-user-card-override/index.js
src/Resources/app/administration/src/sw-order-user-card-override/sw-order-user-card.html.twig
src/Resources/config/services.xml
src/Service/AdyenPaymentService.php

A new section created for the partial payment details. That section contains pspreference, link to customer area, payment tx_variant, amount and currency.
- Single giftcard payment
- Giftcard payment combined with credit card

[PW-8273] Create a section for partial Adyen payments 

---

src/Handlers/CardsPaymentMethodHandler.php
src/Handlers/PaymentResponseHandler.php
src/Resources/config/services.xml
src/ScheduledTask/Webhook/AuthorisationWebhookHandler.php
src/ScheduledTask/Webhook/WebhookHandlerFactory.php
src/Service/PluginPaymentMethodsService.php

Method identifier is being obtained from the webhook's `paymentMethod` object instead of `orderTransaction`. That allows setting different capture modes for partial payments.
- Giftcard payments
- Giftcard + Klarna payments

[PW-8295] Fix giftcard capture mode for adyen_payment table

---

src/Controller/AdminController.php
src/Resources/app/administration/src/component/adyen-payment-capture/index.js
src/Resources/app/administration/src/service/adyenService.js
src/Resources/config/services.xml
src/Resources/config/services/notification-processing.xml
src/ScheduledTask/ProcessNotificationsHandler.php
src/ScheduledTask/Webhook/CaptureWebhookHandler.php
src/ScheduledTask/Webhook/OrderClosedWebhookHandler.php
src/Service/AdyenPaymentService.php
src/Service/CaptureService.php
src/Service/Repository/AdyenPaymentCaptureRepository.php
src/Service/Repository/AdyenPaymentRepository.php

1. In order to capture a payment, full amount should be authorised first.
2. Capture request can be sent from admin order details if only the payment method supports manual capture, full amount is authorised and required amount is not captured yet.
3. If full amount has not been captured successfully (failed capture webhook), sequential capture requests can be sent.
4. Only `requiredCaptureAmount` can be captured for an order. This `requiredCaptureAmount` is obtained from `AdyenPaymentEntity` with manual capture mode payments only.
5. ORDER_CLOSED webhook was fixed for manual capture to use correct merchant reference and capture amount based on the`requiredCaptureAmount` for that transaction.
Notes
1. Manual capture requires the correct shipment state. If that state isn’t satisfied,
- …

[PW-8294] Fix manual capture flow for giftcards

---

src/Migration/Migration1681716164AlterAdyenPayment.php
src/ScheduledTask/Webhook/AuthorisationWebhookHandler.php
src/Service/AdyenPaymentService.php

Unique constraint added to `adyen_payment` table to block duplicate entries for the same (partial or normal) payment.
`AuthorisationWebhookHandler` updated regarding to this requirement.
- Authorisation webhook processing
- Delayed capture after shipment

[PW-8339] Add unique constraint pspreference to adyen_payment table

---

.github/workflows/e2e-test.yml
src/Service/PaymentMethodsFilterService.php
src/Subscriber/PaymentSubscriber.php

In the current flow of the Shopware 6 giftcard implementation, if the full amount is covered by a giftcard, this giftcard payment method appears on the checkout as pre-selected and the shopper can complete the payment.
However, if the shopper selects another payment method, this giftcard payment method disappears from the checkout due to our filtering and it is not possible to select that giftcard payment method again, although the state data is still in the database.
This PR fixes the above so when the shopper selects another payment method in the checkout page, the redeemed giftcard is still shown in the list of payment methods on the mentioned page.
- redeem a giftcard, proceed to the checkout page
- select another payment method and observe the redeemed giftcard still listen in the …

[PW-8325] Allow re-selecting giftcard payment method

---

src/Service/PaymentMethodsFilterService.php

This is a minor update to our fix in #378. After this fix, all giftcard PMs are shown in checkout when the shopper doesn't apply any giftcard.
This fix removes all giftcard payment methods from the checkout and only shows the applicable giftcard when one exists for the shopper's session.

[PW-8325] remove all giftcards from checkout when no giftcard is saved

---

src/Controller/AdminController.php

In cases where the value of `updatedAt` field in the `adyen_notification` db table was null or undefined, this would cause an exception being thrown. The issue is fixed with this PR using a null-coalescing operator, as null-safe operator doesn't work prior to PHP v8.0.
- manually remove the content of the `updatedAt` field of the `adyen_notification` db table and refresh the order review page of the admin panel. Make sure no errors/exceptions are thrown
Fixes #270

[PW-8365] Check if updatedAt exists before formatting in AdminController

---

src/Resources/app/storefront/src/cart/cart.plugin.js

For when redeeming giftcards during checkout, If there is a transaction limit specified, use that as a balance amount instead of the actual balance on the gift card.
1. When product price is less than the transaction limit
2. When product price is greater than the transaction limit
3. When the transaction limit is same as balance

[ECP-8452] Update maximum giftcard discount allowed to transaction limit

---

src/Resources/config/services/notification-processing.xml
src/ScheduledTask/FetchPaymentMethodLogosHandler.php

Since CDN url redirection breaks current implementation to fetch payment method logos, we will continue fetching logos from live endpoint which doesn't use CDN redirection, yet.
- Fetching payment method logos

[ECP-8560] Always use live endpoint for logos

---

src/Subscriber/PaymentSubscriber.php

Fix division by zero error when cart total is zero.
Issue:
```
Issue Description / Steps to Reproduce:
-Create a product with a price of €0 and free shipping (or add a 100% discount)
-Add product to the cart
-500 error is thrown 
```

Fix division by zero error

---

src/Resources/app/storefront/src/checkout/confirm-order.plugin.js
src/Resources/views/storefront/component/adyencheckout.html.twig
src/Subscriber/PaymentSubscriber.php

An implementation of Click-to-pay feature on storefront, which automatically grabs the visa/mastercard token (if it exists) for the current shopper, avoiding the shopper having to manually enter the card details. 
1. Tested with a shopper id that has existing card token
2. Tested with a shopper id that does not

[ECP-8363] Support Click-to-Pay

---

src/Handlers/AbstractPaymentMethodHandler.php
src/Service/CaptureService.php
src/Service/ClientService.php
src/Service/DonationService.php
src/Service/OrdersCancelService.php
src/Service/OrdersService.php
src/Service/PaymentDetailsService.php
src/Service/PaymentMethodsBalanceService.php
src/Service/PaymentMethodsService.php
src/Service/RefundService.php

Logging functionality was removed completely from Adyen PHP API Library. Shopware 6 plugin used to use the logger in the library to log requests and responses. 
API logging functionality migrated to application and library logging dependency removed.

[ECP-8561] Move API logging functionality to plugin

---

src/ScheduledTask/Webhook/WebhookHandlerFactory.php

`CANCELLED` webhook event removed from the plugin due the deprecation in webhook module. Detailed information on event codes can be found on [docs](https://docs.adyen.com/development-resources/webhooks/webhook-types/).
- Webhook processing

[ECP-8574] Remove deprecated CANCELLED webhook event

---

src/Service/PaymentMethodsFilterService.php

This changes prevents a PHP error if the response does not have the array key requested. This is in my opinion necessary as in other places, the code explicitly checks if $adyenPaymentMethods['paymentMethods'] is empty or not.

Prevent PHP error if response is missing data.

---

src/Resources/config/services/subscribers.xml
src/Subscriber/ContextSubscriber.php

After login Shopware triggers `SalesChannelContextRestoredEvent` event to update the cart and remove the guest shopper cart. An event listener was created for this event to change the context token in `adyen_payment_state_data` table. Additional function was added to set the payment method to selected Adyen giftcard as this data disappears as well after the login due to context token change.
- Giftcard payments for guest/logged-in shoppers

[ECP-8333] Fix disappearing giftcard discount data after login

---

src/AdyenPaymentShopware6.php

Add failsafe for assets installation so that plugin installation/activation doesn't fail
Fixes #430

Failsafe assets installation

---

src/Controller/StoreApi/OrderApi/OrderApiController.php
src/Handlers/AbstractPaymentMethodHandler.php
src/Service/PaymentStateDataService.php

Saving multiple giftcard state data is allowed with the new setup. 

[ECP-8327] Saving multiple Statedata

---

src/Entity/PaymentResponse/PaymentResponseEntity.php
src/Entity/PaymentResponse/PaymentResponseEntityDefinition.php
src/Migration/Migration1705588547AlterAdyenPaymentResponse.php
src/Resources/config/services/notification-processing.xml
src/ScheduledTask/ProcessNotificationsHandler.php
src/Service/PaymentResponseService.php
src/Service/Repository/OrderTransactionRepository.php

`Authorisation` webhook for a failed payment attempt is intentionally being processed after 30 minutes after arrival. During this time, order has not been cancelled and expects a successful payment. However, webhook for failed payment attempt overrides the successful authorisation after 30 minutes.
This PR introduces a fix to this issue by fetching the correct `order_transaction` entity for the failed payment attempt. Therefore, successful payment's `order_transaction` is not affected.
- Happy and unhappy flows of card payments with webhook processing
- Processing capture webhook

[ECP-8812] Fix failed authorisation webhook overrides successful payment

---

src/ScheduledTask/FetchPaymentMethodLogosHandler.php

Merchant is on shopware 6.14.2 and they are having an issue where 2 tasks are remaining in queued. This PR solves one of the main issue where fetch_payment_method_logos task is remaining in queued, the logos are not being displayed at checkout. 

[ECP-8821] SW6 Tasks remaining in queued and logos not loading in Checkout

---

src/Controller/StoreApi/Donate/DonateController.php
src/Controller/StoreApi/Payment/PaymentController.php
src/Handlers/AbstractPaymentMethodHandler.php
src/Handlers/Command/DisablePaymentMethodHandler.php
src/Handlers/Command/EnablePaymentMethodHandler.php
src/Handlers/PaymentResponseHandler.php
src/Resources/config/services.xml
src/Resources/config/services/controllers.xml
src/ScheduledTask/FetchPaymentMethodLogosHandler.php
src/ScheduledTask/ProcessNotificationsHandler.php
src/Service/PluginPaymentMethodsService.php

Removing EntityRepository Decorator from everywhere, where it is deprecated
Source of truth: [Shopware6.4](https://github.com/shopware/shopware/blob/trunk/UPGRADE-6.4.md#removed-repository-decorators)
[Shopware6.5](https://github.com/shopware/shopware/blob/trunk/UPGRADE-6.5.md#removed-repository-decorators)

ECP-8856 Shopware 6 - Compatibility Error on Update

---

composer.json
src/Command/DisablePaymentMethodCommand.php
src/Command/EnablePaymentMethodCommand.php
src/Command/FetchPaymentMethodLogosCommand.php
src/Command/ProcessWebhooksCommand.php
src/Controller/AdminController.php
src/Controller/StoreApi/Donate/DonateController.php
src/Controller/StoreApi/OrderApi/OrderApiController.php
src/Controller/StoreApi/Payment/PaymentController.php
src/Handlers/Command/DisablePaymentMethodHandler.php
src/Handlers/PaymentResponseHandler.php
src/Migration/Migration1609373668AdyenMediaFolder.php
src/Resources/config/routes.xml
src/Resources/config/services/controllers.xml
src/Resources/config/services/subscribers.xml
src/Service/Repository/OrderTransactionRepository.php
src/Storefront/Controller/FrontendProxyController.php
src/Storefront/Controller/NotificationReceiverController.php
src/Subscriber/PostPaymentSubscriber.php

Shopware 6.6 migrated to Symfony 7. According to [Symfony 7 change logs](https://github.com/symfony/symfony/blob/7.0/UPGRADE-7.0.md), following changes have been made.
- Controller routes are now using attributes instead of annotations.
- Command definitions have changed.
Following changes have been made as a part of [Shopware 6.6 breaking changes](https://github.com/shopware/shopware/blob/v6.6.0.0-rc1/UPGRADE-6.6.md).
- Dropped DB column `association_fields` was removed from migration file.
- Missing `stateMachineState` association was added to order transaction repository.
- 3DS2 card payments
- iDeal and Klarna redirect payments
- Multibanco voucher payments
- Donations
- Giftcards
- Authorisation webhook processing

[ECP-8935] Support Symfony 7

---

src/Controller/StoreApi/OrderApi/OrderApiController.php
src/Resources/app/storefront/src/cart/cart.plugin.js
src/Resources/config/services.xml
src/Resources/config/services/controllers.xml
src/Resources/views/storefront/component/checkout/cart/giftcards.html.twig
src/Resources/views/storefront/page/checkout/confirm/confirm-payment.html.twig
src/Service/PaymentMethodsFilterService.php
src/Service/PaymentStateDataService.php
src/Storefront/Controller/FrontendProxyController.php
src/Subscriber/PaymentSubscriber.php

While testing there were few flows discovered and they are as:
1. Currently, MultiGiftcard UI on carts page is having a dropdown which when selected loads the giftcard component, but it can be a confusing part for the user, thereby adding a button or link which says, Add Giftcards and then loading the dropdown and component will be more wise solution
2. On the first, landing on checkout page doesn't shows the giftcard paymentMethod and the reason was that it was not setting the PaymentMethod from the subscriber. And as soon as we refresh the page, the flow was all good.
- Changes suggested : If the full amount is covered, then Set the Giftcard PaymentMethod while fetching the redeemedGiftcards instead of the onCheckoutConfirmLoaded of the PaymentSubscriber.
Full multigiftcard flow
**Fixed …

[ECP-9010] Refactor MultiGiftcards UI and the flow for setting Giftcard PM

---

src/Handlers/Command/DisablePaymentMethodHandler.php
src/Handlers/PaymentResponseHandler.php
src/Resources/config/services/controllers.xml

This PR adds the missing dependency injection definition for `order_transaction.repository`. This bug causes not supporting any versions below Shopware 6.4.15.0 since `EntityRepository` is not auto wirable below that version.
- Happy/unhappy flow on Shopware 6.4.12.0 and Shopware 6.5.8.0
Fixes #461

[ECP-9027-v3] Add missing dependency definition

---

src/Command/DisablePaymentMethodCommand.php
src/Command/EnablePaymentMethodCommand.php
src/Command/FetchPaymentMethodLogosCommand.php
src/Command/ProcessWebhooksCommand.php
src/Command/ScheduleWebhooksCommand.php
src/Resources/config/services/commands.xml

The PR add a new command to process schedule webhooks.
In some scenarios Shopware scheduled tasks stops running after restarting php-fpm.
By using console commands via crontab this can be prevented.
Example crontab:
```
* * * * * php bin/console adyen:process-webhooks
* * * * * php bin/console adyen:schedule-webhooks
```

add schedule webhook command

---

src/Storefront/Controller/FrontendProxyController.php

In the `FrontendProxyController::checkoutOrder()` the whole order entity is being put in a `JsonResponse`. If that order has bidirectional associations (for example transactions which also have a reference back to the order, and thus back to the transactions and back to the order etc...) then the `JsonResponse` object will throw an error: "_Recursion detected_"
Just load an order with some bidirectional associations in some subscriber that's triggered on checkout. 
**Fixed issue**:  No issue has been made
The [JS success callback](https://github.com/Adyen/adyen-shopware6/blob/develop/src/Resources/app/storefront/src/checkout/confirm-order.plugin.js#L261-L267) that uses the checkout route response only used the id, so no need to send the whole entity. Just send the id, and that's it.

Fix recursion error for checkout order route

---

src/Controller/AdminController.php

The additional null check allows the method to return early of no Adyen transaction was found instead of relying that an exception is thrown. Because the original intend of the try-catch was to catch any exception, the catch clause is changed to catch all Throwables (possible since PHP 7).
I removed the variable from the catch clause in the first place. But because this plugin has to be compatible with Shopware 6.4, it has to be PHP 7.4 compatible. Catch clauses without variable are allowed since PHP 8.
None
**Fixed issue**:  https://github.com/Adyen/adyen-shopware6/issues/479

Add null check to isManualCaptureEnabled method of AdminController

---

src/Handlers/AbstractPaymentMethodHandler.php
src/Service/PaymentMethodsService.php

Language of shopperLocal stayed to default language and did not update along with updating the language of shopware instance. This resulted in a bug where payment page still stayed to default language as the /payments call had default value in shopperLocale. 
1. On mini cart page for payment methods call
2. On checkout page

[ECP-8827] Fixing shopper locale for redirect based payment methods

---

src/Handlers/AlbelliGiftCardPaymentMethodHandler.php
src/Handlers/BeautyGiftCardPaymentMethodHandler.php
src/Handlers/BijenkorfGiftCardPaymentMethodHandler.php
src/Handlers/DeCadeaukaartGiftCardPaymentMethodHandler.php
src/Handlers/FashionChequeGiftCardPaymentMethodHandler.php
src/Handlers/GallGallGiftCardPaymentMethodHandler.php
src/Handlers/GenericGiftCardPaymentMethodHandler.php
src/Handlers/GivexGiftCardPaymentMethodHandler.php
src/Handlers/HunkemollerLingerieGiftCardPaymentMethodHandler.php
src/Handlers/KadowereldGiftCardPaymentMethodHandler.php
src/Handlers/SVSGiftCardPaymentMethodHandler.php
src/Handlers/TCSTestGiftCardPaymentMethodHandler.php
src/Handlers/VVVGiftCardPaymentMethodHandler.php
src/Handlers/WebshopGiftCardPaymentMethodHandler.php
src/PaymentMethods/AlbelliGiftCardPaymentMethod.php
src/PaymentMethods/BeautyGiftCardPaymentMethod.php
src/PaymentMethods/BijenkorfGiftCardPaymentMethod.php
src/PaymentMethods/DeCadeaukaartGiftCardPaymentMethod.php
src/PaymentMethods/FashionChequeGiftCardPaymentMethod.php
src/PaymentMethods/GallGallGiftCardPaymentMethod.php
src/PaymentMethods/GenericGiftCardPaymentMethod.php
src/PaymentMethods/GivexGiftCardPaymentMethod.php
src/PaymentMethods/HunkemollerLingerieGiftCardPaymentMethod.php
src/PaymentMethods/KadowereldGiftCardPaymentMethod.php
src/PaymentMethods/SVSGiftCardPaymentMethod.php
src/PaymentMethods/TCSTestGiftCardPaymentMethod.php
src/PaymentMethods/VVVGiftCardPaymentMethod.php
src/PaymentMethods/WebshopGiftCardPaymentMethod.php
src/Resources/config/services/payment-handlers.xml

This PR reverts the removed gift card payment method classes and adds them `@deprecated` tag, which blocks running update script to the following version.
- Installing and updating the plugin on Shopware 6.4 and Shopware 6.5

[ECP-9184] Revert removal of gift card payment methods

---

src/AdyenPaymentShopware6.php
src/Controller/StoreApi/Payment/PaymentController.php
src/Handlers/AbstractPaymentMethodHandler.php

Following exception classes were deprecated on Shopware 6.5 and removed on Shopware 6.6. Those exception classes were replaced with `PaymentException`.
- `AsyncPaymentFinalizeException`
- `AsyncPaymentProcessException`
- `CustomerCanceledAsyncPaymentException`
- `PaymentProcessException`
- Redirect payment flows
- Card payments

[ECP-9149] Remove deprecated classes of Shopware

---

src/Migration/Migration1713255011AlterAdyenPayment.php

Merchants sometimes get database syntax error on updating the plugin. This error occurs when the syntax of SQL query in alter table for providing  default value is not compatible with the MYSQL modes being used by the merchant. In this PR we update the syntax to a format that is expected to have more leniency.

[ECP-9226] Update syntax for default value in alter table in migration

---

src/Migration/Migration1713255011AlterAdyenPayment.php

Merchants sometimes get database syntax error on updating the plugin. This error occurs when the syntax of SQL query in alter table for providing default value is not compatible with the MYSQL modes being used by the merchant. In this PR we update the syntax to a format that is expected to have more leniency.

[ECP-9226-v3] Update syntax for default value in alter table in migration

---

src/Controller/AdminController.php
src/Handlers/PaymentResponseHandler.php
src/Resources/app/administration/src/component/adyen-refund/index.js
src/Resources/app/administration/src/service/adyenService.js

Adyen related tables notifications, refunds and captures are not showing up if the payment is completed with gift card payment. This PR contains an updated check for whether an order is an Adyen order based on orderTransaction. If the order is an Adyen-Order the tables would show up regardless of the payment method.

[ECP-9206] Adyen related tables missing for giftcard payments on admin panel

---

src/Resources/app/storefront/src/checkout/confirm-order.plugin.js

As a part of new Visa compliance requirements, `holderName` should be present in card and Card on File recurring payments.
This PR adds `holderName` to `/payments` request body for recurring payments.
Note that, `holderName` field is already added by card component on regular card payments.
- Tokenised card payments should include holder name.

[ECP-9382-v3] Include holderName in recurring payment requests

---

.github/workflows/e2e-test.yml
.github/workflows/templates/docker-compose.playwright.yml
.github/workflows/upload-release-asset.yml
composer.json

Release 4.1.1

---

.github/workflows/upload-release-asset.yml

Zip file uploaded as assets was broken, as the prepare-release-assets.yml was failing due to incorrect php version constraint.
Defining the php version to the workflow.

[ECP-9434]Making changes to release asset yml, passing php version
