- .github/workflows/main.yml
- composer.json
- composer.lock
- phpcs.xml
- src/AdyenPayment.php
- src/Models/OriginKeyModel.php
- src/Service/ClientService.php
- src/Service/ConfigurationService.php
- src/Service/NotificationReceiverService.php
- src/Service/NotificationService.php
- src/Service/OriginKeyService.php
- src/Service/PaymentMethodsService.php
PR as draft while https://github.com/Adyen/adyen-shopware6/pull/8 is merged to make code style conflicts easier to fix.
> Github actions main.yml

- src/Handlers/PaymentResponseHandler.php
- src/Resources/config/services.xml
The handler is [WIP] since it is just an empty shell and does some
logging where necessary
> [PW-2686] Add PaymentResponseHandler.php to handle response resultCodes from Adyen

- src/Controller/SalesChannelApiController.php
- src/Resources/config/services.xml
- src/Service/PaymentDetailsService.php
Create an extra endpoint for the paymentDetails (JUST creating the endpoint)
The endpoint responds with the dummy JSON response
> [PW-2684] Add new /payment-details sales-channel-api endpoint

- composer.json
- composer.lock
Got an error after checking out develop that a builder cannot be found. After this change is merged run Composer update and deploy the new lib.
> Update Adyen php api library to version 7

- src/Handlers/CardsPaymentMethodHandler.php
- src/Handlers/PaymentResponseHandler.php
- src/Resources/config/services.xml
Add PaymentResponseHandler to CardsPaymentMethodHandler
Rejected card payment
> [PW-2739] Handle Error and Rejected result codes

- src/Handlers/PaymentResponseHandler.php
- src/Resources/config/services.xml
Implement Authorised payment result code
> [PW-2685] Implement Authorised payment result code

- src/Handlers/PaymentResponseHandler.php
Implement Received and PresentToShopper payment results
> [PW-2685] Implement Received and PresentToShopper payment results

- src/Controller/SalesChannelApiController.php
- src/Resources/config/services.xml
- src/Service/PaymentResponseService.php
- src/Service/PaymentStatusService.php
Created a new Payment Status endpoint and service to return the action and payment response result code.
NA
**Fixed issue**:  PW-2768
> [PW-2768] Payment Status API endpoint

- src/Resources/app/storefront/src/checkout/confirm-order.plugin.js
- src/Resources/config/services.xml
- src/Resources/views/storefront/component/payment/adyencheckout.html.twig
- src/Resources/views/storefront/page/account/order/index.html.twig
- src/Resources/views/storefront/page/checkout/confirm/confirm-payment.html.twig
- src/Storefront/Controller/AdyenAccountOrderController.php
- src/Subscriber/CheckoutSubscriber.php
- src/Subscriber/PaymentSubscriber.php
> [PW-2755] Handle payments on account/order page

- src/Resources/config/services.xml
- src/Service/ClientService.php
- src/Service/ContainerParametersService.php
Add applicationInfo support
Add getModuleVersion() to retrieve the Adyen module version from the
composer.json file if available
Add ContainerParametersService.php as a helper service to retrieve
parameters from the container
Available version in composer.json
Not available version in composer.json
> [PW-2678] Set applicationInfo data 

- src/Handlers/CardsPaymentMethodHandler.php
- src/Resources/config/services.xml
- src/Storefront/Controller/RedirectResultController.php
Add new endpoint to process redirect results from Adyen /adyen/redirect-result
Replace the original returnUrl with the new endpoint
> [PW-2821] Send the CSRF token to finalize-transaction

- src/Framework/Cookie/AdyenCookieProvider.php
- src/Resources/config/services.xml
- src/Resources/snippet/en_GB/cookie-consent.en-GB.json
Adding Adyen placed cookies into the Shopware Cookie consent list
> [PW-2819] Register Adyen cookies with Shopware cookie consent manager

- src/Handlers/PaymentResponseHandler.php
Fixes the state transition bug for non 3D cards
non 3D card Authorised
non 3D card Refused
3DS2 card authorised
> [PW-2840] Fix illegal transition "paid" from state

- composer.json
- composer.lock
- src/Exception/CurrencyNotFoundException.php
- src/Handlers/AbstractPaymentMethodHandler.php
Shopware marketplace code review shows a warning when this dependency is not in composer.json.
Another warning for a missing Exception class is also being fixed.
Plugin submission to the marketplace.
**Fixed issue**:  PW-2939
> [PW-2939] Adding shopware/storefront dependency

- src/Handlers/KlarnaAccountPaymentMethodHandler.php
- src/PaymentMethods/KlarnaAccountPaymentMethod.php
- src/Resources/app/storefront/src/checkout/checkout.plugin.js
- src/Resources/config/services.xml
Add support for Klarna Account as a new payment method. This is just a declaration of the payment method, most of the heavy work is already implemented in Klarna Pay Now and Klarna Pay Later.
> [PW-2922] Add support for Klarna Account

- src/Handlers/AbstractPaymentMethodHandler.php
- src/Handlers/ResultHandler.php
- src/Storefront/Controller/RedirectResultController.php
This reverts commit eab299fb (#47)
Successful payments with cards.
> Remove GET redirect directive

- src/Resources/snippet/de_DE/cookie-consent.de-DE.json
- src/Resources/snippet/de_DE/messages.de-DE.json
> [PW-3334] Missing German translations for cookie snippet 

- src/Resources/app/storefront/src/checkout/checkout.plugin.js
- src/Resources/app/storefront/src/checkout/confirm-order.plugin.js
- src/Resources/app/storefront/src/configuration/adyen.js
- src/Resources/views/storefront/page/checkout/confirm/confirm-payment.html.twig
- src/Service/PaymentStatusService.php
- src/Subscriber/PaymentSubscriber.php
Show payment selection form when a payment method is selected which requires extra information form the customer before placing an order
Non Adyen payment method
Adyen payment method which requires extra data
Adyen payment method which doesn't require extra data
> [PW-3074] Cards form is not presented to shopper if it is the default payment method

- composer.lock
- src/AdyenPaymentShopware6.php
The new version of the plugin will install and activate storedPaymentMethod when `bin/console plugin:update AdyenPaymentShopware6` is used.
Updating the plugin from 1.1.0 installs and activates storedPaymentMethod
> Plugin update method

- .github/CODEOWNERS
Update codeowners, add @peterojo 
> Add @peterojo to codeowners

- README.md
> Update Readme with supported payment methods list

- src/Resources/config/services.xml
- src/ScheduledTask/ScheduleNotificationsHandler.php
Use the new created `ScheduleNotifications` scheduled tasks to fetch unscheduled notifications and schedule them based on specific criteria
> [PW-3592] Schedule notifications from the shopware ScheduledTask

- .github/CODEOWNERS
PR created to add myself to the codeowners.
> Add myself to the codeowners

- src/Migration/Migration1607529255AdyenNotification.php
Oops! Turns out that you cannot add a column and add a comment to it at the same time. 🙏🏿
> PW-3049 bugfix

- src/Handlers/AbstractPaymentMethodHandler.php
- src/Storefront/Controller/NotificationReceiverController.php
- src/Storefront/Controller/RedirectResultController.php
Fixes: #136
See issue: https://github.com/Adyen/adyen-shopware6/issues/136
> [PW-3124] Correct prefixes for storefront routes to ensure correct routes are generated

- src/Subscriber/PaymentSubscriber.php
For headless implementations with a non-standard payment flow, the `SalesChannelContextSwitchEvent` may be dispatched on multiple steps.
This PR adds a fix to our implementation of saving payment state data, now we will save or clear the payment data only when the payment method is updated.
Standard flow for payment still works.
Triggering the `SalesChannelContextSwitchEvent` without the `paymentMethodId` in the request will skip the `saveStateData()` method
**Fixed issue**: #135
> [PW-4180] save or clear state data only if payment method is updated

- src/Resources/config/services.xml
- src/Resources/config/services/checkout-api.xml
- src/Resources/config/services/controllers.xml
- src/Resources/config/services/models.xml
- src/Resources/config/services/notification-processing.xml
- src/Resources/config/services/payment-handlers/payment-handlers.xml
- src/Resources/config/services/repositories.xml
- src/Resources/config/services/utils.xml
Start separating XML configuration in multiple files to make the file easier to read.
* Installing the plugin from scratch
* Updating the plugin from `develop`
> Refactor services.xml

- src/Handlers/AbstractPaymentMethodHandler.php
When the shopping cart contains items with different tax rates and a discount is applied, then the `getCalculatedTaxes()` value of the discount contains multiple entities, with the current approach of picking the `->first()` taxRate, we get a wrong result and the API returns an error similar to `Acquirer Error (BAD_VALUE : order_lines[6].total_tax_amount)`.
API allows sending the line items without the discount https://docs.adyen.com/payment-methods/klarna/invoice-lines#no-discount-line, so this is the simplest way to solve the problem
Send payment request with multiple line items of different tax rates and apply discount
> [PW-4117] exclude discount from line items in open invoice request

- src/Handlers/AbstractPaymentMethodHandler.php
Changing the format of the date in getBirthday Shopware function. 
**Fixed issue**:  PW-4451
> [PW-4451] - Change the format of the date on getBirthday 

- src/Core/Checkout/Order/Aggregate/OrderTransaction/OrderTransactionExtension.php
- src/Core/Checkout/Payment/PaymentMethod/PaymentMethodExtension.php
- src/Provider/AdyenPluginProvider.php
- src/Resources/config/services.xml
- src/Resources/config/services/providers.xml
- src/Service/PaymentMethodsFilterService.php
- src/Struct/AdyenPaymentMethodDataStruct.php
- src/Subscriber/PaymentSubscriber.php
- src/Subscriber/Response/PaymentMethodRouteResponseSubscriber.php
It adds adyen payment method information to the payment method store API response.
Retrieving payment methods using Store-API.
**Fixed issue**:  #154
> Add payment methods response and additional information to store api response

- src/Resources/config/services.xml
- src/Struct/AdyenContextDataStruct.php
- src/Struct/ContextAdyenDataStruct.php
- src/Subscriber/ContextResolvedSubscriber.php
Added client key to Store API response, so it can be used by a PWA.
> Add client key, environment and has payment state data to context store api response

- .github/CODEOWNERS
> It's not you, it's me.

- src/Controller/ApiTestController.php
- src/Controller/StoreApiController.php
- src/Resources/app/storefront/src/scss/base.scss
- src/Subscriber/PaymentSubscriber.php
Updated service dependencies that were changed in shopware 6.4
Removed version number from store-api URLs according to shopware 6.4 update
> [PW-4690] Update broken service dependencies and store-api URLs

- src/Resources/config/config.xml
This PR updates the configuration panel by separating the existing fields into different sections
* Configuration for live
* Configuration for test
> [PW-4915] - Split the configuration panel into components

- composer.lock
- src/Controller/AdminController.php
- src/Service/RefundService.php
Enabling the merchants to initiate accurate refunds with also non-integer numbers (decimals).
Initiating the refunds with decimal numbers.
**Fixed issue**:  [PW-6169]
> [PW-6169] enable the refunds to be initiated with accurate decimals

- composer.json
- composer.lock
- src/Resources/app/administration/src/main.js
- src/Resources/config/services/checkout-api.xml
- src/ScheduledTask/ProcessNotificationsHandler.php
- src/Service/ClientService.php
- src/Test/bootstrap.php
**Fixes**
- #234 
**Other**
- #228
- #229
- #230
> Release 3.3.1

- src/Exception/CaptureException.php
- src/Resources/app/administration/src/component/entity/sw-entity-single-select-override/index.js
- src/Resources/app/administration/src/main.js
- src/Resources/config/config.xml
- src/Resources/config/services.xml
- src/Resources/config/services/notification-processing.xml
- src/ScheduledTask/ProcessNotificationsHandler.php
- src/Service/CaptureService.php
- src/Service/ConfigurationService.php
Adjusted the notification process handler to do a automated delayed capture for klarna. It is checked if the order delivery is in a configured state, if not the notification gets rescheduled after a configured amount of time.
> Added CaptureService to delay capture for payments

- src/Service/ClientService.php
Adjust the externalPlatform from `Shopware` to `Shopware6`
Card payment in checkout, inspected api.log
> [PW-6516] update platform name

- src/Handlers/AbstractPaymentMethodHandler.php
- src/Resources/config/services/payment-handlers.xml
- src/Resources/views/storefront/page/checkout/confirm/confirm-payment.html.twig
- src/Service/PaymentMethodsService.php
- src/Subscriber/PaymentSubscriber.php
House number and street address separation with regex
Card Payments
Form HPPs (Oney 3x4x)
Redirect HPPs (iDeal, Klarna)
> [PW-6502] - Street name and house number separation with regex

- src/Controller/StoreApiController.php
- src/Handlers/AbstractPaymentMethodHandler.php
- src/Resources/config/services/checkout-api.xml
- src/Service/PaymentRequestService.php
Image and product URLs added for Klarna and other open invoice methods to `lineItem`.
> [PW-6468] - Add image & product Url parameters to lineItem for open invoices

- src/AdyenPaymentShopware6.php
- src/Handlers/BancontactMobilePaymentMethodHandler.php
- src/PaymentMethods/BancontactMobilePaymentMethod.php
- src/PaymentMethods/PaymentMethods.php
- src/Resources/app/storefront/src/configuration/adyen.js
- src/Resources/config/services/payment-handlers.xml
Bancontact Mobile payment method was added.
> [PW-6677] - Add Bancontact Mobile payment method support

- src/Resources/config/config.xml
First part of the Adyen Giving support is creating configuration fields in the admin page.
Add Adyen Giving configuration fields to plugin config page.
> [PW-6813] - Add Adyen Giving configuration fields to plugin config page

- src/ScheduledTask/ProcessNotificationsHandler.php
In order to make troubleshooting a bit easier.
Update the webhook processor to use order number as the identifier in logs and log all errors to notification table.
> [PW-6906] Improve webhook processing logs

- src/Resources/views/storefront/component/payment/adyencheckout.html.twig
- src/Resources/views/storefront/component/payment/payment-action-modal.html.twig
- src/Resources/views/storefront/component/payment/payment-component-modal.html.twig
- src/Resources/views/storefront/component/payment/payment-fields.html.twig
- src/Resources/views/storefront/component/payment/payment-method.html.twig
- src/Resources/views/storefront/page/account/order/index.html.twig
- src/Resources/views/storefront/page/checkout/confirm/confirm-payment.html.twig
- src/Resources/views/storefront/page/checkout/confirm/index.html.twig
Refactors the Twig so it is easier for template developers to extend, Twig is now according to Shopware guidelines
N/A, nothing was broken. It can just be a little bit better 😄 
> Refactor Twig

- src/Resources/app/storefront/src/checkout/confirm-order.plugin.js
Added country code and address data to wallet component config
Pay with paypal and german address
Paypal paylater
> [PW-7014] fix paypal paylater display

- src/Handlers/ResultHandler.php
This PR fixes the issue where giftcard payment were not being completed. By using `payload` instead of `redirectResult` for payment/details API call.
- Giftcards payment
- iDeal payment
- 3DS 1 payment
> [PW-7017] fix for giftcard payments

- src/Handlers/AbstractPaymentMethodHandler.php
Add missing parameters of the line items according to Adyen PHP API Library.
> [PW-7106] - Use lineItem builder in PHP library for lineItems

- src/Controller/StoreApiController.php
- src/Resources/config/services.xml
- src/Service/OrdersCancelService.php
- src/Service/OrdersService.php
- src/Service/PaymentMethodsBalanceService.php
This PR creates API endpoints to check giftcard balance, create order and cancel order through order API for the gift cards partial payment implementation.
Made the following calls with Postman and made sure the responses were successful:
- `/store-api/adyen/payment-methods/balance`
- `/store-api/adyen/orders`
- `/store-api/adyen/orders/cancel`
> [PW-7186] Create REST endpoints for Order API implementation

- src/Exception/CaptureException.php
- src/ScheduledTask/ProcessNotificationsHandler.php
- src/Service/CaptureService.php
Update capture request parameters to skip promotions and other non-product items similarly to the payment request
- Add promotion to cart and pay with klarna (manual capture enabled)
> [PW-7220] skip non product items in capture requests

- .github/release.yml
This PR adds instructions to help Github auto generate release notes based on PR labels
Breaking change
Feature, or
Fix
> Add release yml file for auto generation of release notes

- src/Resources/app/storefront/src/checkout/confirm-order.plugin.js
- src/Resources/views/storefront/page/checkout/confirm/confirm-payment.html.twig
- src/Subscriber/PaymentSubscriber.php
Fix Shopware Affiliate marketing
Tested with Adyen Payment method
Tested without Adyen Payment method
- Set Affiliate marketing
- Unset Affiliate marketing. 
#295
> [PW-7455] - Fix Showpare Affiliate marketing for Adyen Payment Method

- composer.json
- composer.lock
- src/Command/DisablePaymentMethodCommand.php
- src/Command/EnablePaymentMethodCommand.php
- src/Handlers/Command/DisablePaymentMethodHandler.php
- src/Handlers/Command/EnablePaymentMethodHandler.php
- src/Resources/app/storefront/src/checkout/confirm-order.plugin.js
- src/Resources/config/services.xml
- src/Resources/config/services/commands.xml
- src/Resources/views/storefront/page/checkout/confirm/confirm-payment.html.twig
- src/ScheduledTask/Webhook/CancelOrRefundWebhookHandler.php
- src/ScheduledTask/Webhook/CancellableWebhookHandlerTrait.php
- src/ScheduledTask/Webhook/CancellationWebhookHandler.php
- src/ScheduledTask/Webhook/OfferClosedWebhookHandler.php
- src/ScheduledTask/Webhook/WebhookHandlerFactory.php
- src/Subscriber/PaymentSubscriber.php
> Release 3.8.1

- .github/workflows/e2e-test.yml
Fetch logos before starting E2E tests.
> [PW-7623] Payment methods not loading on E2E

- src/Handlers/AbstractPaymentMethodHandler.php
Shopware's [Custom Product](https://docs.shopware.com/en/shopware-6-en/extensions/customproducts) extension allows merchants to sell customised products upon the decision of the shopper. However, those line items are considered as `options` rather than `product` and skipped on the line item builder for open invoice payment methods.
Custom options and selections are supported with this PR and included in the line item builder.
- Klarna w/wo custom product options
> [PW-6244] Support custom product line items

- src/Resources/views/storefront/page/checkout/address/index.html.twig
- src/Subscriber/PaymentSubscriber.php
Giftcard component and giftcard related order summary added to the registration page.
- Happy/unhappy flow with generic giftcard.
> [PW-8156] Load giftcard component on the registration page

- src/Handlers/AbstractPaymentMethodHandler.php
- src/Resources/config/services/payment-handlers.xml
Change payment method after giftcard payments.
> [PW-8075] Change payment method after giftcard payments

- composer.json
- composer.lock
- src/Controller/StoreApi/Donate/DonateController.php
- src/Controller/StoreApi/Payment/PaymentController.php
- src/Subscriber/PaymentSubscriber.php
Shopware 6 static code analyses throws an error for the usage of methods have `@internal` tag on it. Those methods replaced with the correct ones.
- Card payments happy/unhappy flow
- iDeal happy/unhappy flow
- Card failing + ideal success case
- Donation
- Changing the payment method on the checkout
> [PW-8230] Replace the methods designed for internal usage with the correct ones

- renovate.json
Configure Renovate and disable dependency dashboard
> Configure Renovate and disable dependency dashboard

- .github/workflows/e2e-test.yml
This PR adds possibility to run e2e pipeline manually, alongisde the existing probability of automatic trigger for each PR
> [Test] Add manual trigger for e2e tests

- .github/workflows/e2e-test.yml
> Set Adyen Giving configuration fields for actions

- src/Resources/app/storefront/src/cart/cart.plugin.js
- src/Resources/app/storefront/src/checkout/confirm-order.plugin.js
- src/Resources/views/storefront/component/checkout/offcanvas-cart-summary.html.twig
- src/Resources/views/storefront/component/payment/payment-component.html.twig
- src/Subscriber/PaymentSubscriber.php
jQuery usage was replaced with native javascript functions.
- Card payments
- 3DS payments
- Giftcard payments
> [PW-8324] Remove jQuery dependency

- src/Controller/StoreApi/Donate/DonateController.php
Validate donation request:
- Check that currency is the same as original order currency
- Check the donation amount is among the configured donation amounts
> [PW-8404] Validate donation currency and amount

- src/Resources/views/storefront/component/adyencheckout.html.twig
Instead of showing version number, release notes page was referenced.
Related checkout component and API library version can be found in the release notes.
> Update component version comment

- src/Resources/config/services/controllers.xml
Payment processing fails due to missing definition in `controller.xml`. Required argument was added.
- Payment flow
- Notification handling
Fixes #397
> [ECP-8562] Define missing argument for service_container

- composer.json
- src/ScheduledTask/ProcessNotificationsHandler.php
Logging functionality was removed from the latest version of PHP Webhook Module. This PR introduces logging of webhook processor in the application level and upgrades PHP Webhook Module version to 0.8.0.
- Processing notifications
> [ECP-8566] Update webhook module version and log processor result

- src/ScheduledTask/FetchPaymentMethodLogosHandler.php
- src/ScheduledTask/ProcessNotificationsHandler.php
Removing EntityRepository Decorators for the deprecated repository decorators.
> [ECP-8821-2] Modifying the decorators for EntityRepository

- composer.json
> Version bump 3.14.4

- src/Handlers/Command/DisablePaymentMethodHandler.php
Importing the Entity Repository missing class
> ECP-8856 Shopware 6 - Compatibility Error on Update

- src/Resources/app/storefront/src/checkout/confirm-order.plugin.js
- src/Resources/app/storefront/src/scss/base.scss
This PR replaces html element to attribute id to narrow down the scope of the style block and removes a duplicated line.
- Gift card payments
> Fix gift card dropdown CSS attribute

- .github/workflows/e2e-test.yml
- .github/workflows/templates/docker-compose.playwright.yml
Updating the docker-compose command by removing hyphen, to solve the failing docker install command.
> [ECP-9438] Update test flow to update docker install command.

- .github/workflows/upload-release-asset.yml
Revert unused job definition from the workflow.
> Revert changes in release workflow

- src/ScheduledTask/ProcessNotificationsHandler.php
- src/ScheduledTask/ScheduleNotificationsHandler.php
This PR introduces missing scheduled task definition attributes in the scheduled task handlers. This is a critical issue which blocks the webhook scheduling/processing.
- Schedule webhook
- Process webhook
> [ECP-9458] Update the handlers for the scheduled tasks

- src/Service/PaymentMethodsService.php
- src/Subscriber/PaymentSubscriber.php
> Fix the return type error

- .github/workflows/scripts/prepare-release-asset.sh
- .github/workflows/upload-release-asset.yml
* Fixed upload release asset
Full Changelog: https://github.com/Adyen/adyen-shopware6/compare/4.2.2...4.2.3
> Update upload release asset

- composer.json
* Updated version
Full Changelog: https://github.com/Adyen/adyen-shopware6/compare/3.17.3...3.17.4
> Version bump 3.17.4

- composer.json
- src/Handlers/PaymentResponseHandler.php
- src/Resources/snippet/de_DE/messages.de-DE.json
- src/Resources/snippet/en_GB/messages.en-GB.json
- src/Resources/views/storefront/page/checkout/finish/finish-details.html.twig
- src/Subscriber/PostPaymentSubscriber.php
* Add notification message on Thank You page for processing payments
Full Changelog: https://github.com/Adyen/adyen-shopware6/compare/4.2.9...4.2.10
> Prepare release 4.2.10
